# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SHExtensionExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SHExtensionExample

  target 'SHExtensionExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SHExtensionExampleUITests' do
    # Pods for testing
  end

  pod 'GTMBase64'

end
